services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  # Example Postgres service (disabled by default)
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: myproject
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data:
